# Generated by Django 5.0.6 on 2024-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_alter_category_name_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
