# Generated by Django 5.0.6 on 2024-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0005_productvariant_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
