# Generated by Django 5.0.6 on 2024-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0006_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("otp", models.CharField(max_length=255)),
            ],
        ),
    ]
