# Generated by Django 5.0.6 on 2024-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0007_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="user_id",
        ),
        migrations.AddField(
            model_name="otp",
            name="code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_expired",
            field=models.BooleanField(default=True),
        ),
    ]
