# Generated by Django 5.0.6 on 2024-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0008_remove_otp_otp_remove_otp_user_id_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
