# Generated by Django 5.0.6 on 2024-09-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_otp_user_id_alter_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_expired",
        ),
    ]
