# Generated by Django 5.0.6 on 2024-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0014_remove_otp_is_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_otp_expired",
            field=models.BooleanField(default=True),
        ),
    ]
