# Generated by Django 5.0.6 on 2024-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0016_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
