# Generated by Django 5.0.6 on 2024-09-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0019_address_delete_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
