# Generated by Django 5.0.6 on 2024-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0020_address_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
