# Generated by Django 5.0.6 on 2024-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0023_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="variant",
            field=models.IntegerField(null=True),
        ),
    ]
