# Generated by Django 5.0.6 on 2024-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0024_alter_wishlist_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.IntegerField(null=True),
        ),
    ]
