# Generated by Django 5.0.6 on 2024-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0026_rename_variant_cartitem_variant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variant_id",
            field=models.IntegerField(default="", null=True),
        ),
    ]
