# Generated by Django 5.0.6 on 2024-09-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0027_alter_cartitem_variant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variant_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userapp.productvariant",
            ),
        ),
    ]
