# Generated by Django 5.0.6 on 2024-09-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0028_remove_cartitem_variant_id_cartitem_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variantdetials",
                to="userapp.productvariant",
            ),
        ),
    ]
