# Generated by Django 5.0.6 on 2024-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0029_alter_cartitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="img",
            field=models.URLField(null=True),
        ),
    ]
