# Generated by Django 5.0.6 on 2024-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0030_cartitem_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
