# Generated by Django 5.0.6 on 2024-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0034_remove_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="img",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
