# Generated by Django 5.0.6 on 2024-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0035_orderitem_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
