# Generated by Django 5.0.6 on 2024-09-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0036_orderitem_created_at_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
