# Generated by Django 5.0.6 on 2024-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0037_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="user_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
