# Generated by Django 5.1.1 on 2024-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0038_orderitem_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_product_price",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
