# Generated by Django 5.1.1 on 2024-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0039_orderitem_total_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="no method specified", max_length=100),
        ),
    ]
