# Generated by Django 5.1.1 on 2024-09-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0040_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userapp.productvariant",
            ),
        ),
    ]
