# Generated by Django 5.1.1 on 2024-09-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0041_alter_wishlist_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="imageurl",
            field=models.URLField(null=True),
        ),
    ]
