# Generated by Django 5.1.1 on 2024-09-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0042_wishlist_imageurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="coupon_type",
            new_name="discountType",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="discount",
            new_name="discountValue",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="expiration_date",
            new_name="expiryDate",
        ),
        migrations.AddField(
            model_name="coupon",
            name="selectedCategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="selectedProduct",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
