# Generated by Django 5.1.1 on 2024-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0044_alter_coupon_limit_alter_coupon_selectedcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discountValue",
            field=models.IntegerField(),
        ),
    ]
