# Generated by Django 5.1.1 on 2024-09-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0045_alter_coupon_discountvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="selectedCategory",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="selectedProduct",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userapp.product",
            ),
        ),
    ]
