# Generated by Django 5.1.1 on 2024-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0046_alter_coupon_selectedcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="use_count",
            field=models.IntegerField(default=0),
        ),
    ]
