# Generated by Django 5.1.1 on 2024-09-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0047_coupon_use_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discountSection",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="selectedCategory",
            field=models.ForeignKey(
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="selectedProduct",
            field=models.ForeignKey(
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userapp.product",
            ),
        ),
    ]
