# Generated by Django 5.1.1 on 2024-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userapp",
            "0048_coupon_discountsection_alter_coupon_selectedcategory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
