# Generated by Django 5.1.1 on 2024-09-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0049_coupon_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="coupon",
            field=models.ForeignKey(
                max_length=250,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userapp.coupon",
            ),
        ),
    ]
