# Generated by Django 5.1.1 on 2024-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0050_orderitem_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_payed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="paymenttype",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
