# Generated by Django 5.1.1 on 2024-09-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0051_orderitem_is_payed_orderitem_paymenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=50)),
                (
                    "orderitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="userapp.orderitem",
                    ),
                ),
            ],
        ),
    ]
