# Generated by Django 5.1.1 on 2024-09-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0055_walletamount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="orderitem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userapp.orderitem",
            ),
        ),
    ]
