# Generated by Django 5.1.1 on 2024-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0056_alter_wallet_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
