# Generated by Django 5.1.1 on 2024-10-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0057_address_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="reason",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
